tab = int(input("Qual tabuada deseja:"))
print("\n")
print("a tabuada é:")
print(tab,"x 1 =",tab*1)
print(tab,"x 2 =",tab*2)
print(tab,"x 3 =",tab*3)
print(tab,"x 4 =",tab*4)
print(tab,"x 5 =",tab*5)
print(tab,"x 6 =",tab*6)
print(tab,"x 7 =",tab*7)
print(tab,"x 8 =",tab*8)
print(tab,"x 9 =",tab*9)
print(tab,"x 10 =",tab*10)

